<a href="https://colab.research.google.com/github/rajasreena1999/rajasreenarepository/blob/main/Python_Numpyarray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Numpy.array()**
The homogeneous multidimensional array is the main object of NumPy. It is basically a table of elements which are all of the same type and indexed by a tuple of positive integers. The dimensions are called **axis **in NumPy.

The NumPy's array class is known as **ndarray **or **alias array**. The numpy.array is not the same as the standard Python library class array.array. The array.array handles only one-dimensional arrays and provides less functionality.

Syntax

    numpy.array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)

**Parameters**

1) object: array_like

Any object, which exposes an array interface whose __array__ method returns any nested sequence or an array.

2) dtype : optional data-type

This parameter is used to define the desired parameter for the array element. If we do not define the data type, then it will determine the type as the minimum type which will require to hold the object in the sequence. This parameter is used only for upcasting the array.

3) copy: bool(optional)

If we set copy equals to true, the object is copied else the copy will be made when an object is a nested sequence, or a copy is needed to satisfy any of the other requirements such as dtype, order, etc.

4) order : {'K', 'A', 'C', 'F'}, optional

The order parameter specifies the memory layout of the array. When the object is not an array, the newly created array will be in C order (row head or row-major) unless 'F' is specified. When F is specified, it will be in Fortran order (column head or column-major). When copy=False or the copy is made for the other reason, the result will be the same as copy= True with some exceptions for A. The default order is 'K'.

5) subok : bool(optional)

When subok=True, then sub-classes will pass-through; otherwise, the returned array will force to be a base-class array (default).

6) ndmin : int(optional)

This parameter specifies the minimum number of dimensions which the resulting array should have. Users can be prepended to the shape as needed to meet this requirement.

In [ ]:
import numpy as np
ar1=np.array([1,2,3])
ar1


array([1, 2, 3])

In [ ]:
ar2 = np.array([1,2.,3.])
ar3=np.array([[1,2,3],[4,5,6]])
print(ar2)
print(ar3)

[1. 2. 3.]
[[1 2 3]
 [4 5 6]]


In [ ]:
#check datatype
import numpy as np
arr1 = np.array([10, 11, 12, 13])
print(arr1.dtype)
arr2 = np.array(['Matlab','in', '8', 'Hours'])
print(arr2.dtype)

int64
<U6


“arr1.dtype” and “arr2.dtype” returns the data type of the arrays.“int64” means the integer type with 64 bits.“<U6” means that each unsigned string has no more than six characters in this array (Matlab in 8 Hours).“<” is a symbol of the little-endian byte order.

In [ ]:
import numpy as np
myArr = np.array([10, 20, 30, 40], dtype='S')
print(myArr.dtype)

|S2


“dtype='S” sets the data type of the array to be a string.“|”symbol means that it's not applicable to use the byte order symbol here.“S2” means that the array data type is String, the size of the each element is2 bytes.

**Convert Integer Type**

The syntax to convert the data type of an array is:

    myArr.astype(‘data_type’)

In [ ]:
import numpy as np
myArr = np.array([0.99, 1.99, 2.99, 3.99])
print(myArr.dtype)
arr = myArr.astype('i')
print(arr)
print(arr.dtype)

float64
[0 1 2 3]
int32


In [ ]:
myarr=np.array([1,2,3],'S')
print(myarr.dtype)
arr1=myarr.astype('i')
print(arr1.dtype)

|S1
int32


In [ ]:
import numpy as np
myArr = np.array([0, 1, 2, 3])
arr = myArr.astype(bool)
print(arr)
print(arr.dtype)

[False  True  True  True]
bool


In [ ]:
#minimum dimensions
import numpy as np
arr=np.array([1,2.,3.],ndmin=2)
arr

array([[1., 2., 3.]])

In [ ]:
#type provided
import numpy as np
arr=np.array([12,45.,3.],dtype=complex)
arr

array([12.+0.j, 45.+0.j,  3.+0.j])

In [ ]:
#creating an array from sub-classes
import numpy as np
arr1=np.array(np.mat('1 2;3 4'))
arr2=np.array(np.mat('1 2;3 4'),subok=True)
# arr1
arr2

matrix([[1, 2],
        [3, 4]])

In [ ]:
#create an array filled with 0’s
array1=np.zeros(2)
print(array1)

#or an array filled with ones
array2=np.ones(3)
print(array2)

[0. 0.]
[1. 1. 1.]


In [ ]:
#create an empty array
a1=np.empty(4)
print(a1)

[4.9e-324 9.9e-324 1.5e-323 2.0e-323]


The function empty creates an array whose initial content is random and depends on the state of the memory. The reason to use empty over zeros (or something similar) is speed - just make sure to fill every element afterwards!

**Zero-Dimensional Array**

A Zero-Dimensional array is called a scalar, its element is only a value.The syntax to create a zero-dimensional array is:

    myArray = np.array(value)

In [ ]:
import numpy as np
myArray = np.array(100)
print(myArray)   #np.array(100)” creates a zero-dimensional array with a value 100.

100


In [ ]:
arr1=np.array(45)
arr1

array(45)

In [ ]:
#create an array with range of elements

a1=np.arange(5)
#array that contains a range of evenly spaced intervals. To do this, you will specify the first number, last number, and the step size
a2=np.arange(2,9,2)
print(a1)
print(a2)

[0 1 2 3 4]
[2 4 6 8]


In [ ]:
#create an array with values that are spaced linearly in a specified interval,number=no of samples

a1=np.linspace(0,10,num=7)
print(a1)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.        ]


**Two-Dimensional Array**

A Two-Dimensional Array contains multiple one-dimensional arrays.The syntax to create a two-dimensional array is:

    myArray = np.array( [ [v1, v2, v3] , [v4, v5, v6] ] )

In [ ]:
import numpy as np
myArray = np.array([[0, 1, 2], [3, 4, 5]])
print(myArray)

[[0 1 2]
 [3 4 5]]


**Three-Dimensional Array**

A Three-Dimensional Array contains multiple two-dimensional arrays.The syntax to create a three-dimensional array is:

    myArr = np.array( [[[v1, v2, v3] , [v4, v5, v6], [v7, v8, v9]]] )

In [ ]:
import numpy as np
myArr = np.array([[[0,1,2], [3,4,5], [6,7,8]]])
print(myArr)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [ ]:
#sorting elements
a1=np.array([5,4,6,8,1])
np.sort(a1)

array([1, 4, 5, 6, 8])

In addition to sort, which returns a sorted copy of an array, you can use:


**argsort**- which is an indirect sort along a specified axis



**lexsort**- which is an indirect stable sort on multiple keys.

**searchsorted**-  which will find elements in a sorted array.

**partition**-  which is a partial sort.

In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
#You can concatenate them with np.concatenate().

np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
#You can concatenate them with:

np.concatenate((x, y.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

###How do you know the shape and size of an array?
This section covers ndarray.ndim, ndarray.size, ndarray.shape

**ndarray.ndim** will tell you the number of axes, or dimensions, of the array.

**ndarray.size** will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

**ndarray.shape** will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [ ]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
import numpy as np
arr0 = np.array(100)      # 0d array
arr1 = np.array([0, 1, 2, 3, 4, 5])      # 1d array
arr2 = np.array([[0, 1, 2], [3, 4, 5,]])      # 2d array
arr3 = np.array([[[0,1,2], [3,4,5], [6,7,8]]])      # 3d array
print(arr0.ndim)
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

0
1
2
3


**nditer()**

To get each actual element value (scalar), we can use nditer() to iterate
through all elements in the array. The syntax is:

    nditer(myArray)

In [ ]:
import numpy as np
myArr = np. array([[10, 11, 12], [13, 14, 15]])
for num in np.nditer(myArr):      # myArr is a 2d array
print(num)

**Access Two-Dimensional Array**


We can access a two-dimensional array by index.A two-dimensional array contains multiple rows and columns.The syntax to access a 2-d array with rows and columns is:

    myArray[ row, col ]

In [ ]:
import numpy as np
arr = np.array([[10,11,12,13,14], [15,16,17,18,19]])
print ('The value in row 0 and col 3 is:', arr[0,3])
print ('The value in row 1 and col 2 is:', arr[1,2])

The value in row 0 and col 3 is: 13
The value in row 1 and col 2 is: 17


**Iterating with Step**

 Length Iterating with step length is mainly used in the 2-d array.The syntax of the step length is:

    nditer( myArr[ :,: :step ] )

In [ ]:
import numpy as np
myArr = np.array([[10, 11, 12, 13], [14, 15, 16, 17]])
for num in np.nditer(myArr[:,: :2]):
  print(num)

#“nditer(myArr[:,::2])” sets up a step length, by which NumPy Iteratingthrough every scalar element of the array, each step skips 1 element.

10
12
14
16


**Enumerating the Array**

We can specify a sequence number to each element in an array.

    ndenumerate(myArray)

In [ ]:
import numpy as np
myArr = np.array([0, 1, 2, 3])
for id, num in np.ndenumerate(myArr):
  print(id, num)

(0,) 0
(1,) 1
(2,) 2
(3,) 3


**Last Index**

We can use “-1” to represent the last index.

    myArray[-1, -1]       # access the last row and the last col

In [ ]:
import numpy as np
arr = np.array([[10,11,12,13,14], [15,16,17,18,19]])
print('The value in row 0 and the last col is:', arr[0,-1])
print('The value in the last row and col 2 is:', arr[-1,2])
print('The value in the last row & the last col is:', arr[-1,-1])

The value in row 0 and the last col is: 14
The value in the last row and col 2 is: 17
The value in the last row & the last col is: 19


In [ ]:
array_example.size

24

In [ ]:
array_example.shape # 2 rows,3 matrix,4 column

(3, 2, 4)

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a.shape

(3, 4)

In [ ]:
import numpy as np
myArr = np.array([1, 2, 3, 4, 5,6], ndmin=3)
print(myArr)
print('The array shape is:', myArr.shape)

[[[1 2 3 4 5 6]]]
The array shape is: (1, 1, 6)


In [ ]:
import numpy as np
myArr = np.array([[0,1,2,3],[4,5,6,7],[2,4,6,8]])
print(myArr.shape)

(3, 4)


**High Dimension Array **

The syntax to define a higher dimension array is:

ndmin = number

The “number” means how many dimensions in an array.

In [ ]:
import numpy as np
# define 3d array
arr3 = np.array([ 0, 1, 2, 3 ], ndmin=3)
# define 4th array
arr4 = np.array([ 0, 1, 2, 3 ], ndmin=4)
# define 5th array
arr5 = np.array([ 0, 1, 2, 3 ], ndmin=5)

print(arr3)
print(arr4)
print(arr5)

[[[0 1 2 3]]]
[[[[0 1 2 3]]]]
[[[[[0 1 2 3]]]]]


**How to reshape an array**

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array

In [ ]:
a = np.arange(6)
print(a)
b = a.reshape(3, 2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [ ]:
import numpy as np
myArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
newArr = myArr.reshape(3, 4)
print(newArr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np
myArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
newArr = myArr.reshape(3, 4)
print(newArr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
import numpy as np
myArr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
newArr = myArr.reshape(2, 2, 3)
print(newArr)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


The result is a 3-d array, which contains two 2-d arrays with 2 rows ofelements and 3 columns of elements.

Reshape Requirement

The requirement of the array reshape is:The number of elements in the original array must equal the product ofthe dimensions.

In [ ]:
arr.reshape( 2, 6 )      # 2*6=12
arr.reshape( 3, 4 )      # 3*4=12
arr.reshape( 4, 3 )      # 4*3=12
#......
#When it is reshaped to a 3-d array:
#we can use:
arr.reshape( 1, 3, 4 )     # 1*3*4=12
arr.reshape( 2, 3, 2 )     # 2*3*2=12
arr.reshape( 3, 2, 2 )     # 3*2*2=12......

**Unknown Dimension**

If we do not specify an exact number for one of the dimensions in thereshape method, we can use “-1” as a parameter.NumPy will calculate thisnumber automatically.Three syntaxes are:

* arr.reshape( -1, rows, columns )

* arr.reshape( layer, -1, columns )

* arr.reshape( layer, rows, -1)

In [ ]:
import numpy as np
myArr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newArr = myArr.reshape( -1, 2, 3 )
print(newArr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
b=np.reshape(a, newshape=(1, 6), order='C')
print(b)


[[0 1 2 3 4 5]]


**newshape** is the new shape you want. You can specify an integer or a tuple of integers. If you specify an integer, the result will be an array of that length. The shape should be compatible with the original shape.

**order**: C means to read/write the elements using C-like index order, F means to read/write the elements using Fortran-like index order, A means to read/write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise. (This is an optional parameter and doesn’t need to be specified.)

 Essentially, C and Fortran orders have to do with how indices correspond to the order the array is stored in memory. In **Fortran**, when moving through the elements of a two-dimensional array as it is stored in memory, the **first index** is the most rapidly varying index. As the first index moves to the next row as it changes, the matrix is stored one column at a time. This is why Fortran is thought of as a **Column-major language**. In C on the other hand, the **last index** changes the most rapidly. The matrix is stored by rows, making it a **Row-major language**.

**Flattening Array**

 means reshaping the multiple dimensional array to a 1-darray.The syntax to reshape an array into a 1-d array is:

    myArr.reshape(-1)

In [ ]:
import numpy as np
myArr = np.array([[1,2,3], [4,5,6], [7,8,9]])
newArr = myArr.reshape(-1)
print(newArr)

[1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np
myArr = np.array([10, 11, 12])
for num in myArr:
  print(num)

myArr1 = np.array([[10, 11, 12], [13, 14, 15]])
for num1 in myArr1:
  print(num1)

10
11
12
[10 11 12]
[13 14 15]


###How to convert a 1D array into a 2D array (how to add a new axis to an array)
You can use **np.newaxis** and **np.expand_dims** to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [ ]:
a = np.array([1, 2, 3, 4, 5])
print(a.shape)
a2 = a[np.newaxis, :]
print(a2.shape)


(5,)
(1, 5)


In [ ]:
  #You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis.
  #For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:
row_vector = a[np.newaxis, :]

print(row_vector)
print(row_vector.shape)

  #for a column vector, you can insert an axis along the second dimension:
col_vector = a[:, np.newaxis]

print(col_vector)
print(col_vector.shape)

[[1 2 3 4 5]]
(1, 5)
[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [ ]:
#You can use np.expand_dims to add an axis at index position 1 with
b = np.expand_dims(a, axis=1)
print(b.shape)
c = np.expand_dims(a, axis=0)
print(c.shape)

(5, 1)
(1, 5)


**Indexing and slicing**

In [ ]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2
[1 2]
[2 3]
[2 3]


In [ ]:
import numpy as np
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])
print(arr[ :5])
print(arr[5: ])

[10 11 12 13 14]
[15 16 17 18]


In [ ]:
# Negative slicing

import numpy as np
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18])
print(arr[-5 : -2])
print(arr[-7 : -3])

[14 15 16]
[12 13 14 15]


In [ ]:
#2D array slicing

import numpy as np
arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])
print(arr[0:2, 2:4])

#arr[0:2, 2:4]” returns the elements from row0 to row2-1, and from col2 tocol4-1.

[[12 13]
 [17 18]]


In [ ]:
import numpy as np
arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])
print(arr[0, 1:4])
print(arr[1, 2:4])

[11 12 13]
[17 18]


In [ ]:
import numpy as np
arr = np.array([[10, 11, 12, 13, 14], [15,16,17,18,19]])
print(arr[0:2, 2])
print(arr[0:1, 3])

[12 17]
[13]


In [ ]:
#print all of the values in the array that are less than 5.
print(a[a < 5])

#numbers that are equal to or greater than 5, and use that condition to index an array.
five_up = (a >= 5)
print(a[five_up])


#You can select elements that are divisible by 2
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

#you can select elements that satisfy two conditions using the & and | operators:

c = a[(a > 2) & (a < 11)]
print(c)


[1 2 3 4]
[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]


In [ ]:
# You can also make use of the logical operators & and | in order to return boolean values that specify whether or not the values in an array fulfill a certain condition.
# This can be useful with arrays that contain names or other categorical values.

five_up = (a > 5) | (a == 5)
print(five_up)

#You can use np.nonzero() to print the indices of elements that are, for example, less than 5:

b = np.nonzero(a < 5)
print(b)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]
(array([0, 0, 0, 0]), array([0, 1, 2, 3]))


In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

In [ ]:
#If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them.
#For example:

list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [ ]:
#If the element you’re looking for doesn’t exist in the array, then the returned array of indices will be empty. For example:

not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


####How to create an array from existing data

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
#You can create a new array from a section of your array any time by specifying where you want to slice your array.

arr1 = a[3:8]
arr1

array([4, 5, 6, 7, 8])

In [ ]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
#You can stack them vertically with vstack:

print(np.vstack((a1, a2)))

#Or stack them horizontally with hstack:

print(np.hstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [ ]:
#If you wanted to split this array into three equally shaped arrays, you would run:

x = np.arange(1, 25).reshape(2, 12)
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [ ]:
#If you wanted to split your array after the third and fourth column, you’d run:

np.hsplit(x, (3, 4))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4],
        [16]]),
 array([[ 5,  6,  7,  8,  9, 10, 11, 12],
        [17, 18, 19, 20, 21, 22, 23, 24]])]

**Copy an array**

In [ ]:
#You can use the view method to create a new array object that looks at the same data as the original array (a shallow copy).

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

#Now we create an array b1 by slicing a and modify the first element of b1. This will modify the corresponding element in a as well!

b1 = a[0, :]
print(b1)

#Using the copy method will make a complete copy of the array and its data (a deep copy).

b2 = a.copy()
print(b2)


[1 2 3 4]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
import numpy as np
arr1 = np.array([0, 1, 2, 3, 4])
# arr1 is an original array
arr2 = arr1.view()
 # arr2 is a view
arr2[0] = 100
print(arr1)
print(arr2)

[100   1   2   3   4]
[100   1   2   3   4]


In [ ]:
import numpy as np
arr1 = np.array([0, 1, 2, 3, 4])    # arr1 is an original array
arr2 =arr1.copy()       # arr2 is a new array
arr2[0] = 100
print(arr1)
print(arr2)

[0 1 2 3 4]
[100   1   2   3   4]


**Check Correlation**

“array.base” can check the correlation of the new array and the old array.If the newArray is copied from the oldArray, then the “newArray.base”will return “None”.

If the newArray is the view of the oldArray, then the “newArray.base”will return a new array.

In [ ]:
import numpy as np
myArr = np.array([0, 1, 2, 3, 4])
copyArr = myArr.copy()
viewArr = myArr.view()
print(copyArr.base)
print(viewArr.base)

None
[0 1 2 3 4]


**Calculate the Element Values**

We can calculate the element's value of an array by using the array index.

In [ ]:
import numpy as np
myArray = np.array([10, 11, 12, 13, 14])
print(myArray[0] + myArray[3])
print(myArray[1] * myArray[2])
print(myArray[0]/myArray[4])

23
132
0.7142857142857143


**Concatenating Arrays**

Concatenating Arrays mean joining elements of two or more arrays into asingle array.The syntax to concatenate arrays is:

    np.concatenate((array1, array2))

In [ ]:
import numpy as np
a1 = np.array([0, 1, 2])
a2 = np.array([3, 4, 5])
myArr = np.concatenate((a1, a2))
print(myArr)

[0 1 2 3 4 5]


When concatenating two arrays, we will use a parameter “axis”.

* axis = 0  join two arrays vertically axis = 1     
* axis = 1  join two arrays horizontally

**Stack Arrays** (axis=0)

The stack() can join two arrays, but it joins two 1-d arrays to be one 2-darray, and joins two 2-d arrays to be one 3-d array.The 1st syntax to stack two arrays is:

    np.stack((array1, array2), axis=0)

In [ ]:
import numpy as np
a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])
myArr = np.stack((a1, a2), axis=0)
print(myArr)

[[[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]]


Stack Arrays (**axis=1**)

The stack() can join two arrays, but it joins two 1-d arrays to be one 2-darray, and joins two 2-d arrays to be one 3-d array.The 2nd syntax to stack two arrays is:

    np.stack((array1, array2), axis=1)

In [ ]:
import numpy as np
a1 = np.array([[11,12,13], [14,15,16]])
a2 = np.array([[21,22,23], [24,25,26]])
myArr = np.stack((a1, a2), axis=1)
print(myArr)

[[[11 12 13]
  [21 22 23]]

 [[14 15 16]
  [24 25 26]]]


Join Arrays **Vertically**

The vstack() can join two arrays vertically.The syntax is:

    np.vstack((array1, array2))

In [ ]:
import numpy as np
a1= np.array([[10,11,12],[13,14,15]])
a2=np.array([[21,22,23],[24,25,26]])
a3=np.vstack((a1,a2))
print(a3)

[[10 11 12]
 [13 14 15]
 [21 22 23]
 [24 25 26]]


Join Arrays **Horizontally**

The hstack() can join two arrays horizontally.The syntax is:

    np.hstack((array1, array2))

In [ ]:
import numpy as np
a1= np.array([[10,11,12],[13,14,15]])
a2=np.array([[21,22,23],[24,25,26]])
a3=np.hstack((a1,a2))
print(a3)

[[10 11 12 21 22 23]
 [13 14 15 24 25 26]]


*Join 1d Arrays to be 3d Array*

We can join two 1d arrays to be one 3d array.The syntax is:

    np.dstack((array1,array2))

By default, “dstack()” join two arrays horizontally.



In [ ]:
import numpy as np
a1=np.array([11,12,13])
a2=np.array([15,16,17])
a3=np.dstack((a1,a2))
print(a3)

[[[11 15]
  [12 16]
  [13 17]]]


In [ ]:
#Join 2d Arrays to be 3d Array

import numpy as np
a1 = np.array([[11],[12],[13]])      # 2d array
a2 = np.array([[14],[15],[16]])      # 2d array
myArr = np.dstack((a1,a2))
print(myArr)

[[[11 14]]

 [[12 15]]

 [[13 16]]]


**Sorting Array**

In [ ]:
#Sorting number array
import numpy as np
myArr = np.array([[ 2, 0, 3, 1 ], [ 7, 5, 6, 4 ]])
print(np.sort(myArr))

In [ ]:
#Sorting string array
import numpy as np
myArr = np.array(['dove', 'buffalo', 'antilope','camel'])
print(np.sort(myArr))

**Split an Array**

Splitting an Array means breaking one array into multiple arrays.The syntax to split one array is:

    array_split( array, number)

The parameter “number” means how many arrays will be split.

In [ ]:
import numpy as np
myArr = np.array([10, 20, 30, 40, 50, 60])
arr = np.array_split(myArr, 3)
print(arr)

[array([10, 20]), array([30, 40]), array([50, 60])]


In [ ]:
#Split Less Elements
#If the array element is not enough to split evenly, NumPy will adjust themautomatically


import numpy as np
a1=np.array([12,15,17,18,19,27])
arr=np.array_split(a1,4)
print(arr)     #“np.array_split(a1, 4)” splits a1 into 4 arrays, but last two arrays only have one element.Because NumPy can automatically adjust them.

[array([12, 15]), array([17, 18]), array([19]), array([27])]


In [ ]:
#Split 2D arrays
import numpy as np
myArr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])     # 2d array
arr = np.array_split(myArr, 2)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


**Split Vertically**

We can split an array vertically.The syntax to split an array vertically is:

    vsplit(array, number)
    
The parameter “number” means how many arrays will be split.

In [ ]:
import numpy as np

myArr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])     # 2d array
arr = np.vsplit(myArr, 2)
print(arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]])]


**Split Horizontally**

We can split an array horizontally.The syntax to split an array horizontally is:

    hsplit(array, number)

The parameter “number” means how many arrays will be split.

In [ ]:
import numpy as np
myArr = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])     # 2d array
arr = np.hsplit(myArr, 2)
print(arr)

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


**Find Array Index**

We can find out the matched indexes by the element value, and return a newarray containing matched indexes.The syntax to find out the matched indexes is:

    where(array == value)

In [ ]:
import numpy as np
myArr = np.array([0, 3, 2, 3, 4, 5, 3])
arr = np.where(myArr == 3)
print(arr)      #“np.where(myArr == 3)” finds out all indexes whose value is 3, andreturns a new array whose elements are matched indexes, which also meansthat the value 3 appears at index 1, 3 and 6.

(array([1, 3, 6]),)


*Where is Even/Odd Number?*

In [ ]:
#We can find out the indexes where the even numbers or the odd numberslocate.
import numpy as np
myArr = np.array([ 10, 55, 21, 62, 29, 75, 36, 98])
even = np.where(myArr%2==0)
print(even)
odd = np.where(myArr%2==1)
print(odd)

(array([0, 3, 6, 7]),)
(array([1, 2, 4, 5]),)


**Search Index in a Location**

In a sorted array, we can search an index by using a value that is not in thecurrent array.The syntax is:

    searchsorted( array, value )

In [ ]:
import numpy as np
myArr = np.array([24, 35, 46, 57, 68])
arr1 = np.searchsorted(myArr, 45)
arr2 = np.searchsorted(myArr, 47)
print(arr1)
print(arr2)

2
3


**Search More Indexes**

We can search multiple indexes simoutaneously.The syntax to search multiple indexes is:

    searchsorted( array, [v1, v2, v3,...] )